version: '3.3'

services:
  nginx:
    image: an.matsenko/frontend_foodgram:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static_django/
      - media_value:/var/html/media/
    depends_on:
      - web
    networks:
      - foodgram_network

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    networks:
      - foodgram_network

  web:
    image: an.matsenko/backend_foodgram:latest
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ../data:/usr/src/app/data
      - static_value:/usr/src/app/web/static_django/
      - media_value:/usr/src/app/web/media/
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - foodgram_network

networks:
  foodgram_network:
    driver: bridge

volumes:
  postgres_data:
  static_value:
  media_value: